apiVersion: v2
name: mlflow-seldon-model
description: Chart to deploy an MLFlow machine learning model to Kubernetes with Seldon Core.
keywords:
- kubernetes
- machine-learning
appVersion: 0.0.1
version: 0.2.0